name: Deploy
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - name: Deploy
        run: |
          echo Installing dependencies...
          npm install
          echo Setting environment variables...
          echo ${{ secrets.PORT }} >> .env
          echo ${{ secrets.DB_CLIENT }} >> .env
          echo ${{ secrets.DB_HOST }} >> .env
          echo ${{ secrets.DB_USER }} >> .env
          echo ${{ secrets.DB_PASSWORD }} >> .env
          echo ${{ secrets.DB_NAME }} >> .env
          echo Building...
          npm run build
          echo Deploying...
          pm2 reload std-feedback-backend
          ${{ secrets.RELOAD_SCRIPT }}
